server:
  port: 8001
  servlet:
    context-path: /api


spring:
  data:
    mongodb:
      uri: mongodb+srv://ddrangers:Atlas12345@cluster0.ceasijp.mongodb.net/Tourify_DB

  jackson:
    time-zone: Europe/Dublin
    date-format: yyyy-MM-dd HH:mm:ss




