server:
  port: 8001
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb+srv://ddrangers:Atlas12345@cluster0.ceasijp.mongodb.net/Tourify_DB

  security:
    oauth2:
      client:
        registration:
          google:
            # Dave:
#            client-id: 568208948795-5dv85a002gctb076vpor6905ur987is0.apps.googleusercontent.com
#            client-secret: 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
            # YJ:
            client-id: 577463964795-efjr0ld5rmvvlamp117jfrovhqh0utcn.apps.googleusercontent.com
            client-secret: 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
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  jackson:
    time-zone: Europe/Dublin
    date-format: yyyy-MM-dd HH:mm:ss